### ISSUE TITLE
Data Sample Request

### ISSUE THREAD

**Issue by 7Vyshak7** [GElpida/feature-extraction-from-ladybug-camera#1]
Hi @GElpida.. 
Thank you for this excellent repo for extracting real world coordinate from the ladybug camera images. It would be much appreciated if you could provide some datasets to test this repo.

**Comment by GElpida** [comment]
Hi @7Vyshak7,
I'm glad you liked my repo. I'm afraid I can't provide you with any data.

**Comment by 7Vyshak7** [comment]
Hi @GElpida,
Thanks For the Reply.. 
Actually I have all the data you mentioned in the **data/Ladybug5_plus**. The only one I want to know how the **pointname.csv** will look like(format). I have used YOLO for the detection and just want to make sure the input goes correct by comparing the input you are passing.

**Comment by GElpida** [comment]
Hi @7Vyshak7, 
Sorry for the delay.
Here is an example of how a pointname.csv will look like.

[bench.csv](https://github.com/user-attachments/files/16090168/bench.csv)

**Comment by GElpida** [comment]
The rectified coordinates are real numbers because they have been calculated with the "ladybugRectifyPixel" function included in Ladybug API.

**Comment by 7Vyshak7** [comment]
@GElpida 
Thank You so Much for this... I will create an input from my own side with YOLO detection and will Try..

**Comment by 7Vyshak7** [comment]
Hi @GElpida..
Are you Planning to add Any data in the **Kalamata_20220413-02_TBC_TMX_export_panorama.csv**??

**Comment by GElpida** [comment]
Hi @7Vyshak7,

I'm not planning to add any more data. 

The **Kalamata_20220413-02_TBC_TMX_export_panorama.csv** is an output file of the [Trimble Business Center software](https://geospatial.trimble.com/en/products/software/trimble-business-center). Unfortunately, I don't own the data, so I uploaded the file empty just to show its structure.
